name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{matrix.os}}
      PYTHON: ${{matrix.python-version}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install poetry tox tox-gh-actions
      - name: Run the tests
        run: tox -e py,py-matplotlib,coverage
      - name: Rename the coverage report
        if: matrix.os == 'windows-latest'
        run: move .coverage.xml .coverage.py${{matrix.python-version}-${{matrix.os}}.xml
      - name: Rename the coverage report
        if: matrix.os != 'windows-latest'
        run: mv .coverage.xml .coverage.py${{matrix.python-version}-${{matrix.os}}.xml
      - name: Upload the coverage report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: .coverage.py{{$matrix.python-version}-${{matrix.os}}.xml
          retention-days: 1
  codecov:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: coverage-reports
          path: reports/
      - uses: codecov/codecov-action@v2
        if: ${{github.event_name == 'push'}}
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          directory: reports/
